github_username: bwa-book

# Site wide configuration

# url: http://watchosapps.build
title: Build watchOS Apps
description: > # this means to ignore newlines until "baseurl:"
  A guide to creating apps for watchOS.
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Mark Goody and Maurice Kelly
  email: bwa-book@watchosapps.build
  twitter: watchOSapps
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
